# Generated by Django 5.2.4 on 2025-07-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('sci-fi', 'Sci-Fi'), ('biography', 'Biography'), ('fantasy', 'Fantasy'), ('romance', 'Romance'), ('history', 'History'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
